export const techTerms = [
  "algorithm",
  "artificial intelligence",
  "big data",
  "blockchain",
  "cloud computing",
  "computer vision",
  "cybersecurity",
  "data mining",
  "data structure",
  "deep learning",
  "devops",
  "distributed systems",
  "encryption",
  "ethical hacking",
  "full stack development",
  "git",
  "graph theory",
  "hashing",
  "internet of things (IoT)",
  "machine learning",
  "natural language processing",
  "networking",
  "object-oriented programming (OOP)",
  "operating system",
  "parallel computing",
  "programming language",
  "quantum computing",
  "recursive function",
  "robotics",
  "scalability",
  "search engine optimization (SEO)",
  "software engineering",
  "virtual reality (VR)",
  "web development",
  "agile methodology",
  "bioinformatics",
  "compiler",
  "cryptography",
  "data compression",
  "data warehousing",
  "embedded systems",
  "functional programming",
  "game development",
  "human-computer interaction (HCI)",
  "microservices",
  "network security",
  "open source",
  "predictive analytics",
  "serverless computing",
  "user experience (UX) design",
  "version control",
];
